import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";
import Navbar from "../components/Navbar/NavBar";
import "./globals.css"; // import NavbarAdmin from "../components/Navbar/navbar-admin/NavBarAdmin";
import { BurgerMenuProvider } from "../components/Navbar/BurgerMenu/BurgerMenuContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <BurgerMenuProvider>
          <Header />
          <Navbar />
          {/* <NavbarAdmin /> */}
        </BurgerMenuProvider>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
