import Header from "../components/Header";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {/* <header>
          <p>header</p>
        </header> */}
        {children}
        <footer>
          <p>foooter</p>
        </footer>
      </body>
    </html>
  );
}
