import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";
import Navbar from "../components/Navbar/Navbar";
import { BurgerMenuProvider } from "../components/Navbar/BurgerMenuContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <BurgerMenuProvider>
          <Header />
          <Navbar />
        </BurgerMenuProvider>
        {children}
        <Footer />
      </body>
    </html>
  );
}
